JoppeDc\SyliusBetterSeoPlugin\Entity\SeoTranslation:
    type: entity
    table: joppedc_seo_translation
    oneToOne:
        image:
            targetEntity: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoImage
            mappedBy: owner
            cascade: [ALL]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pageTitle:
            column: seo_page_title
            type: string
            nullable: true
            options:
                default: ''
        ogTitle:
            column: seo_og_title
            type: string
            nullable: true
            options:
                default: ''
        ogDescription:
            column: seo_og_description
            type: string
            nullable: true
            options:
                default: ''
        twitterTitle:
            column: seo_twitter_title
            type: string
            nullable: true
            options:
                default: ''
        twitterDescription:
            column: seo_twitter_description
            type: string
            nullable: true
            options:
                default: ''
        twitterSite:
            column: seo_twitter_site
            type: string
            nullable: true
            options:
                default: ''
        extraTags:
            column: seo_extra_tags
            type: string
            nullable: true
            options:
                default: ''
        autoTwitterDescription:
            column: auto_twitter_description
            type: boolean
            nullable: true
        autoTwitterTitle:
            column: auto_twitter_title
            type: boolean
            nullable: true
        autoOpengraphDescription:
            column: auto_opengraph_description
            type: boolean
            nullable: true
        autoOpengraphTitle:
            column: auto_opengraph_title
            type: boolean
            nullable: true
